//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.10 at 03:54:46 PM CEST 
//


package osh.configuration.oc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for algorithmType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="algorithmType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="gGA"/&gt;
 *     &lt;enumeration value="ssGA"/&gt;
 *     &lt;enumeration value="DE"/&gt;
 *     &lt;enumeration value="PSO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "algorithmType")
@XmlEnum
public enum AlgorithmType {

    @XmlEnumValue("gGA")
    G_GA("gGA"),
    @XmlEnumValue("ssGA")
    SS_GA("ssGA"),
    DE("DE"),
    PSO("PSO");
    private final String value;

    AlgorithmType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AlgorithmType fromValue(String v) {
        for (AlgorithmType c: AlgorithmType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
