//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.01 at 07:36:51 PM CEST 
//


package osh.configuration.oc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for LoggingConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoggingConfiguration"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="logObjectiveBest" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="logQualityIndicators" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="logParetoFront" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="logRanking" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="qualityIndicators" type="{http://osh/configuration/oc}QualityIndicatorConfiguration" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoggingConfiguration", propOrder = {
    "logObjectiveBest",
    "logQualityIndicators",
    "logParetoFront",
    "logRanking",
    "qualityIndicators"
})
public class LoggingConfiguration {

    protected boolean logObjectiveBest;
    protected boolean logQualityIndicators;
    protected boolean logParetoFront;
    protected boolean logRanking;
    protected List<QualityIndicatorConfiguration> qualityIndicators;

    /**
     * Gets the value of the logObjectiveBest property.
     * 
     */
    public boolean isLogObjectiveBest() {
        return logObjectiveBest;
    }

    /**
     * Sets the value of the logObjectiveBest property.
     * 
     */
    public void setLogObjectiveBest(boolean value) {
        this.logObjectiveBest = value;
    }

    /**
     * Gets the value of the logQualityIndicators property.
     * 
     */
    public boolean isLogQualityIndicators() {
        return logQualityIndicators;
    }

    /**
     * Sets the value of the logQualityIndicators property.
     * 
     */
    public void setLogQualityIndicators(boolean value) {
        this.logQualityIndicators = value;
    }

    /**
     * Gets the value of the logParetoFront property.
     * 
     */
    public boolean isLogParetoFront() {
        return logParetoFront;
    }

    /**
     * Sets the value of the logParetoFront property.
     * 
     */
    public void setLogParetoFront(boolean value) {
        this.logParetoFront = value;
    }

    /**
     * Gets the value of the logRanking property.
     * 
     */
    public boolean isLogRanking() {
        return logRanking;
    }

    /**
     * Sets the value of the logRanking property.
     * 
     */
    public void setLogRanking(boolean value) {
        this.logRanking = value;
    }

    /**
     * Gets the value of the qualityIndicators property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualityIndicators property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualityIndicators().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualityIndicatorConfiguration }
     * 
     * 
     */
    public List<QualityIndicatorConfiguration> getQualityIndicators() {
        if (qualityIndicators == null) {
            qualityIndicators = new ArrayList<QualityIndicatorConfiguration>();
        }
        return this.qualityIndicators;
    }

}
