//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.10 at 03:54:46 PM CEST 
//


package osh.configuration.oc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the osh.configuration.oc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: osh.configuration.oc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OCConfiguration }
     * 
     */
    public OCConfiguration createOCConfiguration() {
        return new OCConfiguration();
    }

    /**
     * Create an instance of {@link GlobalControllerConfiguration }
     * 
     */
    public GlobalControllerConfiguration createGlobalControllerConfiguration() {
        return new GlobalControllerConfiguration();
    }

    /**
     * Create an instance of {@link GlobalObserverConfiguration }
     * 
     */
    public GlobalObserverConfiguration createGlobalObserverConfiguration() {
        return new GlobalObserverConfiguration();
    }

    /**
     * Create an instance of {@link EAConfiguration }
     * 
     */
    public EAConfiguration createEAConfiguration() {
        return new EAConfiguration();
    }

    /**
     * Create an instance of {@link AlgorithmConfiguration }
     * 
     */
    public AlgorithmConfiguration createAlgorithmConfiguration() {
        return new AlgorithmConfiguration();
    }

    /**
     * Create an instance of {@link StoppingRuleConfiguration }
     * 
     */
    public StoppingRuleConfiguration createStoppingRuleConfiguration() {
        return new StoppingRuleConfiguration();
    }

    /**
     * Create an instance of {@link LoggingConfiguration }
     * 
     */
    public LoggingConfiguration createLoggingConfiguration() {
        return new LoggingConfiguration();
    }

    /**
     * Create an instance of {@link OperatorConfiguration }
     * 
     */
    public OperatorConfiguration createOperatorConfiguration() {
        return new OperatorConfiguration();
    }

    /**
     * Create an instance of {@link QualityIndicatorConfiguration }
     * 
     */
    public QualityIndicatorConfiguration createQualityIndicatorConfiguration() {
        return new QualityIndicatorConfiguration();
    }

    /**
     * Create an instance of {@link SolutionRanking }
     * 
     */
    public SolutionRanking createSolutionRanking() {
        return new SolutionRanking();
    }

    /**
     * Create an instance of {@link CostConfiguration }
     * 
     */
    public CostConfiguration createCostConfiguration() {
        return new CostConfiguration();
    }

}
