//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.26 at 12:23:09 AM CET 
//


package osh.configuration.oc;

import osh.configuration.system.ConfigurationParameter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for StoppingRuleConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StoppingRuleConfiguration"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stoppingRuleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ruleParameters" type="{http://osh/configuration/system}ConfigurationParameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StoppingRuleConfiguration", propOrder = {
    "stoppingRuleName",
    "ruleParameters"
})
public class StoppingRuleConfiguration {

    @XmlElement(required = true)
    protected String stoppingRuleName;
    protected List<ConfigurationParameter> ruleParameters;

    /**
     * Gets the value of the stoppingRuleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoppingRuleName() {
        return stoppingRuleName;
    }

    /**
     * Sets the value of the stoppingRuleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoppingRuleName(String value) {
        this.stoppingRuleName = value;
    }

    /**
     * Gets the value of the ruleParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ruleParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRuleParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigurationParameter }
     * 
     * 
     */
    public List<ConfigurationParameter> getRuleParameters() {
        if (ruleParameters == null) {
            ruleParameters = new ArrayList<ConfigurationParameter>();
        }
        return this.ruleParameters;
    }

}
