//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 05:56:34 PM CEST 
//


package osh.configuration.system;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeviceTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="HVAC"/&gt;
 *     &lt;enumeration value="COMBINATIONAPPARATUS"/&gt;
 *     &lt;enumeration value="AIRCONDITION"/&gt;
 *     &lt;enumeration value="FANHEATER"/&gt;
 *     &lt;enumeration value="DISHWASHER"/&gt;
 *     &lt;enumeration value="DRYER"/&gt;
 *     &lt;enumeration value="WASHERDRYER"/&gt;
 *     &lt;enumeration value="WASHINGMACHINE"/&gt;
 *     &lt;enumeration value="ELECTRICOVEN"/&gt;
 *     &lt;enumeration value="ELECTRICSTOVE"/&gt;
 *     &lt;enumeration value="ELECTRICCOOKTOP"/&gt;
 *     &lt;enumeration value="INDUCTIONCOOKTOP"/&gt;
 *     &lt;enumeration value="GASOVEN"/&gt;
 *     &lt;enumeration value="GASSTOVE"/&gt;
 *     &lt;enumeration value="GASCOOKTOP"/&gt;
 *     &lt;enumeration value="COOKERHOOD"/&gt;
 *     &lt;enumeration value="MICROWAVE"/&gt;
 *     &lt;enumeration value="STEAMER"/&gt;
 *     &lt;enumeration value="BREADMAKER"/&gt;
 *     &lt;enumeration value="COFFEESYSTEM"/&gt;
 *     &lt;enumeration value="COFFEEMAKER"/&gt;
 *     &lt;enumeration value="FREEZERREFRIGERATOR"/&gt;
 *     &lt;enumeration value="FREEZER"/&gt;
 *     &lt;enumeration value="REFRIGERATOR"/&gt;
 *     &lt;enumeration value="WINECOOLER"/&gt;
 *     &lt;enumeration value="ELECTRICWATERBOILER"/&gt;
 *     &lt;enumeration value="WATERHEATERINSTANTANEOUS"/&gt;
 *     &lt;enumeration value="WATERHEATERSTORAGE"/&gt;
 *     &lt;enumeration value="LUMINAIRE"/&gt;
 *     &lt;enumeration value="ECAR"/&gt;
 *     &lt;enumeration value="EBIKE"/&gt;
 *     &lt;enumeration value="SEGWAY"/&gt;
 *     &lt;enumeration value="SMARTMETER"/&gt;
 *     &lt;enumeration value="TEMPERATURESENSOR"/&gt;
 *     &lt;enumeration value="GASSENSOR"/&gt;
 *     &lt;enumeration value="SMOKESENSOR"/&gt;
 *     &lt;enumeration value="MOTIONSENSOR"/&gt;
 *     &lt;enumeration value="CONTACTSENSOR"/&gt;
 *     &lt;enumeration value="METERPLUG"/&gt;
 *     &lt;enumeration value="SWITCHPLUG"/&gt;
 *     &lt;enumeration value="METERSWITCHPLUG"/&gt;
 *     &lt;enumeration value="VIRTUALSWITCH"/&gt;
 *     &lt;enumeration value="CHPPLANT"/&gt;
 *     &lt;enumeration value="PVSYSTEM"/&gt;
 *     &lt;enumeration value="HEATPUMP"/&gt;
 *     &lt;enumeration value="IR"/&gt;
 *     &lt;enumeration value="BASELOAD"/&gt;
 *     &lt;enumeration value="HOUSEHOLD"/&gt;
 *     &lt;enumeration value="HOTWATERSTORAGE"/&gt;
 *     &lt;enumeration value="COLDWATERSTORAGE"/&gt;
 *     &lt;enumeration value="ADSORPTIONCHILLER"/&gt;
 *     &lt;enumeration value="SPACECOOLING"/&gt;
 *     &lt;enumeration value="SPACEHEATING"/&gt;
 *     &lt;enumeration value="OTHER"/&gt;
 *     &lt;enumeration value="BATTERYSTORAGE"/&gt;
 *     &lt;enumeration value="GASHEATING"/&gt;
 *     &lt;enumeration value="INSERTHEATINGELEMENT"/&gt;
 *     &lt;enumeration value="DOMESTICHOTWATER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DeviceTypes")
@XmlEnum
public enum DeviceTypes {

    HVAC,
    COMBINATIONAPPARATUS,
    AIRCONDITION,
    FANHEATER,
    DISHWASHER,
    DRYER,
    WASHERDRYER,
    WASHINGMACHINE,
    ELECTRICOVEN,
    ELECTRICSTOVE,
    ELECTRICCOOKTOP,
    INDUCTIONCOOKTOP,
    GASOVEN,
    GASSTOVE,
    GASCOOKTOP,
    COOKERHOOD,
    MICROWAVE,
    STEAMER,
    BREADMAKER,
    COFFEESYSTEM,
    COFFEEMAKER,
    FREEZERREFRIGERATOR,
    FREEZER,
    REFRIGERATOR,
    WINECOOLER,
    ELECTRICWATERBOILER,
    WATERHEATERINSTANTANEOUS,
    WATERHEATERSTORAGE,
    LUMINAIRE,
    ECAR,
    EBIKE,
    SEGWAY,
    SMARTMETER,
    TEMPERATURESENSOR,
    GASSENSOR,
    SMOKESENSOR,
    MOTIONSENSOR,
    CONTACTSENSOR,
    METERPLUG,
    SWITCHPLUG,
    METERSWITCHPLUG,
    VIRTUALSWITCH,
    CHPPLANT,
    PVSYSTEM,
    HEATPUMP,
    IR,
    BASELOAD,
    HOUSEHOLD,
    HOTWATERSTORAGE,
    COLDWATERSTORAGE,
    ADSORPTIONCHILLER,
    SPACECOOLING,
    SPACEHEATING,
    OTHER,
    BATTERYSTORAGE,
    GASHEATING,
    INSERTHEATINGELEMENT,
    DOMESTICHOTWATER;

    public String value() {
        return name();
    }

    public static DeviceTypes fromValue(String v) {
        return valueOf(v);
    }

}
