//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.23 at 08:52:10 PM CET 
//


package osh.configuration.system;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceClassification.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeviceClassification">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HVAC"/>
 *     &lt;enumeration value="APPLIANCE"/>
 *     &lt;enumeration value="LUMINAIRE"/>
 *     &lt;enumeration value="ELECTRICVEHICLE"/>
 *     &lt;enumeration value="METERING"/>
 *     &lt;enumeration value="SENSOR"/>
 *     &lt;enumeration value="SMARTPLUG"/>
 *     &lt;enumeration value="VIRTUALSWITCH"/>
 *     &lt;enumeration value="CHPPLANT"/>
 *     &lt;enumeration value="PVSYSTEM"/>
 *     &lt;enumeration value="HEATPUMP"/>
 *     &lt;enumeration value="BASELOAD"/>
 *     &lt;enumeration value="REMOTECONTROL"/>
 *     &lt;enumeration value="CUSTOMER"/>
 *     &lt;enumeration value="OTHER"/>
 *     &lt;enumeration value="BATTERYSTORAGE"/>
 *     &lt;enumeration value="N/A"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "DeviceClassification")
@XmlEnum
public enum DeviceClassification {

    HVAC("HVAC"),
    APPLIANCE("APPLIANCE"),
    LUMINAIRE("LUMINAIRE"),
    ELECTRICVEHICLE("ELECTRICVEHICLE"),
    METERING("METERING"),
    SENSOR("SENSOR"),
    SMARTPLUG("SMARTPLUG"),
    VIRTUALSWITCH("VIRTUALSWITCH"),
    CHPPLANT("CHPPLANT"),
    PVSYSTEM("PVSYSTEM"),
    HEATPUMP("HEATPUMP"),
    BASELOAD("BASELOAD"),
    REMOTECONTROL("REMOTECONTROL"),
    CUSTOMER("CUSTOMER"),
    OTHER("OTHER"),
    BATTERYSTORAGE("BATTERYSTORAGE"),
    @XmlEnumValue("N/A")
    N_A("N/A");
    private final String value;

    DeviceClassification(String v) {
        this.value = v;
    }

    public static DeviceClassification fromValue(String v) {
        for (DeviceClassification c : DeviceClassification.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return this.value;
    }

}
