//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.05 at 04:33:16 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://osh/configuration/system", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package osh.configuration.system;
