//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.23 at 08:52:10 PM CET 
//


package osh.configuration.appliance;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for XsdLoad complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XsdLoad">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MinValue" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MaxValue" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="commodity" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XsdLoad", propOrder = {
        "value",
        "minValue",
        "maxValue"
})
public class XsdLoad {

    @XmlElement(name = "Value")
    protected int value;
    @XmlElement(name = "MinValue")
    protected Integer minValue;
    @XmlElement(name = "MaxValue")
    protected Integer maxValue;
    @XmlAttribute(name = "commodity", required = true)
    protected String commodity;

    /**
     * Gets the value of the value property.
     */
    public int getValue() {
        return this.value;
    }

    /**
     * Sets the value of the value property.
     */
    public void setValue(int value) {
        this.value = value;
    }

    /**
     * Gets the value of the minValue property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getMinValue() {
        return this.minValue;
    }

    /**
     * Sets the value of the minValue property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMinValue(Integer value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the maxValue property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getMaxValue() {
        return this.maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMaxValue(Integer value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the commodity property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCommodity() {
        return this.commodity;
    }

    /**
     * Sets the value of the commodity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCommodity(String value) {
        this.commodity = value;
    }

}
