//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.01 at 07:36:51 PM CEST 
//


package osh.configuration.appliance;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for xsd.Program complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xsd.Program"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProgramID" type="{http://osh/configuration/appliance}byte"/&gt;
 *         &lt;element name="ProgramName" type="{http://osh/configuration/appliance}name" minOccurs="0"/&gt;
 *         &lt;element name="Descriptions" type="{http://osh/configuration/appliance}XsdDescriptions" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xsd.Program", propOrder = {
    "programID",
    "programName",
    "descriptions"
})
public class XsdProgram {

    @XmlElement(name = "ProgramID")
    protected int programID;
    @XmlElement(name = "ProgramName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String programName;
    @XmlElement(name = "Descriptions")
    protected XsdDescriptions descriptions;

    /**
     * Gets the value of the programID property.
     * 
     */
    public int getProgramID() {
        return programID;
    }

    /**
     * Sets the value of the programID property.
     * 
     */
    public void setProgramID(int value) {
        this.programID = value;
    }

    /**
     * Gets the value of the programName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramName() {
        return programName;
    }

    /**
     * Sets the value of the programName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramName(String value) {
        this.programName = value;
    }

    /**
     * Gets the value of the descriptions property.
     * 
     * @return
     *     possible object is
     *     {@link XsdDescriptions }
     *     
     */
    public XsdDescriptions getDescriptions() {
        return descriptions;
    }

    /**
     * Sets the value of the descriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdDescriptions }
     *     
     */
    public void setDescriptions(XsdDescriptions value) {
        this.descriptions = value;
    }

}
