//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.31 at 07:51:52 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://osh/Simulation/Screenplay", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package osh.simulation.screenplay;
