//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.05 at 04:33:16 PM CEST 
//


package osh.simulation.screenplay;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PerformAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PerformAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actionParameterCollection" type="{http://osh/Simulation/Screenplay}ActionParameters" maxOccurs="unbounded"/>
 *         &lt;element name="appendAction" type="{http://osh/Simulation/Screenplay}SubjectAction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PerformAction", propOrder = {
    "actionParameterCollection",
    "appendAction"
})
public class PerformAction {

    @XmlElement(required = true)
    protected List<ActionParameters> actionParameterCollection;
    protected List<SubjectAction> appendAction;

    /**
     * Gets the value of the actionParameterCollection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionParameterCollection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionParameterCollection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionParameters }
     * 
     * 
     */
    public List<ActionParameters> getActionParameterCollection() {
        if (actionParameterCollection == null) {
            actionParameterCollection = new ArrayList<ActionParameters>();
        }
        return this.actionParameterCollection;
    }

    /**
     * Gets the value of the appendAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appendAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppendAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubjectAction }
     * 
     * 
     */
    public List<SubjectAction> getAppendAction() {
        if (appendAction == null) {
            appendAction = new ArrayList<SubjectAction>();
        }
        return this.appendAction;
    }

}
