//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.23 at 08:52:10 PM CET 
//


package osh.simulation.screenplay;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for SubjectAction complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SubjectAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tick" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="periodicAction" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="periodicRefresh" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="actionType" type="{http://osh/Simulation/Screenplay}ActionType"/>
 *         &lt;element name="deviceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nextState" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="performAction" type="{http://osh/Simulation/Screenplay}PerformAction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectAction", propOrder = {
        "tick",
        "periodicAction",
        "periodicRefresh",
        "actionType",
        "deviceID",
        "nextState",
        "performAction"
})
public class SubjectAction {

    protected long tick;
    @XmlElement(defaultValue = "false")
    protected boolean periodicAction;
    @XmlElement(defaultValue = "0")
    protected int periodicRefresh;
    @XmlElement(required = true)
    protected ActionType actionType;
    @XmlElement(required = true)
    protected String deviceID;
    protected boolean nextState;
    protected List<PerformAction> performAction;

    /**
     * Gets the value of the tick property.
     */
    public long getTick() {
        return this.tick;
    }

    /**
     * Sets the value of the tick property.
     */
    public void setTick(long value) {
        this.tick = value;
    }

    /**
     * Gets the value of the periodicAction property.
     */
    public boolean isPeriodicAction() {
        return this.periodicAction;
    }

    /**
     * Sets the value of the periodicAction property.
     */
    public void setPeriodicAction(boolean value) {
        this.periodicAction = value;
    }

    /**
     * Gets the value of the periodicRefresh property.
     */
    public int getPeriodicRefresh() {
        return this.periodicRefresh;
    }

    /**
     * Sets the value of the periodicRefresh property.
     */
    public void setPeriodicRefresh(int value) {
        this.periodicRefresh = value;
    }

    /**
     * Gets the value of the actionType property.
     *
     * @return possible object is
     * {@link ActionType }
     */
    public ActionType getActionType() {
        return this.actionType;
    }

    /**
     * Sets the value of the actionType property.
     *
     * @param value allowed object is
     *              {@link ActionType }
     */
    public void setActionType(ActionType value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the deviceID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDeviceID() {
        return this.deviceID;
    }

    /**
     * Sets the value of the deviceID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeviceID(String value) {
        this.deviceID = value;
    }

    /**
     * Gets the value of the nextState property.
     */
    public boolean isNextState() {
        return this.nextState;
    }

    /**
     * Sets the value of the nextState property.
     */
    public void setNextState(boolean value) {
        this.nextState = value;
    }

    /**
     * Gets the value of the performAction property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the performAction property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerformAction().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PerformAction }
     */
    public List<PerformAction> getPerformAction() {
        if (this.performAction == null) {
            this.performAction = new ArrayList<>();
        }
        return this.performAction;
    }

}
