//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.26 at 12:23:09 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://osh/configuration/grid", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package osh.configuration.grid;
