//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.12 at 10:41:11 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://osh/configuration/eal", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package osh.configuration.eal;
